<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5FuF4RJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5FuF4RJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5FuF4RJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5FuF4RJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5FuF4RJ\App_KernelDevDebugContainer([
    'container.build_hash' => '5FuF4RJ',
    'container.build_id' => 'efe706c2',
    'container.build_time' => 1674811426,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5FuF4RJ');
